name: Sync Git and SVN Repositories
on: push
jobs:
  sync_git_svn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install git-svn and SVN
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository ppa:git-core/ppa
          sudo apt-get update
          sudo apt-get install -y git-svn expect

      - name: Create SVN Authentication File
        run: |
          mkdir -p ~/.subversion/auth/svn.simple
          cat <<EOF > ~/.subversion/auth/svn.simple/fba5e44bd62f064c71637fd742f1764d
          K 15
          svn:realmstring
          V 71
          <https://svn.informatik.uni-rostock.de:443> SVN  - ITMZ / IFI (Windows)
          K 8
          username
          V 6
          ${SVN_USERNAME}
          K 8
          passtype
          V 6
          simple
          K 8
          password
          V 64
          ${SVN_PASSWORD}
          END
          EOF
  
      - name: Sync changes from Git to SVN
        env:
          SVN_REPO_URL: ${{ secrets.SVN_REPO_URL }}
        run: |
          git svn init "https://${SVN_REPO_URL}" --trunk=trunk --branches=branches --tags=tags --username ${SVN_USERNAME}
          git svn fetch
          git rebase remotes/git-svn
          git svn dcommit

      - name: Sync changes from SVN to Git
        run: |
          git svn fetch
          git rebase remotes/git-svn
          git push