name: Sync Git and SVN Repositories
on: push
env:
  SVN_PASSWORD: ${{ vars.SVN_PASSWORD }}
  SVN_USERNAME: ${{ vars.SVN_USERNAME }}
  SVN_REPO_URL: ${{ vars.SVN_REPO_URL }}
jobs:
  sync_git_svn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install git-svn and SVN
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository ppa:git-core/ppa
          sudo apt-get update
          sudo apt-get install -y git-svn expect

      - name: Create SVN Authentication File
        run: |
          mkdir -p ~/.subversion/auth/svn.simple
          cat <<EOF > ~/.subversion/auth/svn.simple/fba5e44bd62f064c71637fd742f1764d
          K 15
          svn:realmstring
          V 71
          <https://svn.informatik.uni-rostock.de:443> SVN  - ITMZ / IFI (Windows)
          K 8
          username
          V 6
          ${SVN_USERNAME}
          K 8
          passtype
          V 6
          simple
          K 8
          password
          V 64
          ${SVN_PASSWORD}
          END
          EOF
  
      - name: Initialize SVN repo in Git
        run: |
          git svn init ${SVN_REPO_URL} -T trunk -b branches -t tags --username ${SVN_USERNAME}
        
      - name: Fetch SVN revisions into Git
        run: |
          git svn fetch || { echo "Failed to fetch from SVN"; exit 1; }
      
      - name: Verify SVN Branch Exists
        run: |
          if ! git show-ref --quiet remotes/git-svn; then
            echo "Error: 'remotes/git-svn' branch does not exist. Check SVN layout or permissions.";
            exit 1;
          fi
      
      - name: Rebase Git branch with SVN
        run: |
          git rebase remotes/git-svn

      - name: Dcommit
        run: |
          git svn dcommit

      - name: Sync changes from SVN to Git
        run: |
          git svn fetch
          git rebase remotes/git-svn
          git push
