name: Sync Git and SVN Repositories
on: push
jobs:
  sync_git_svn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install git-svn and SVN
        run: |
          sudo apt-get update
          sudo apt-get remove git git-svn
          sudo apt-get autoremove
          sudo apt-get clean
          sudo apt-get install -y git-svn subversion

      - name: Sync changes from Git to SVN
        run: |
          # Set up the SVN repository as a git-svn remote
          git svn init https://${{ secrets.SVN_USERNAME }}:${{ secrets.SVN_PASSWORD}}@${{ secrets.SVN_REPO_URL}} --trunk=trunk --branches=branches --tags=tags
          git svn fetch
          
          # Make sure the latest changes are fetched and synced
          git rebase remotes/git-svn

          # Push changes from Git to SVN
          git svn dcommit
          
      - name: Sync changes from SVN to Git
        run: |
          # Ensure that we're up to date with the SVN repo
          git svn fetch

          # Sync SVN changes to the local Git repo
          git rebase remotes/git-svn

          # Commit and push any changes to Git
          git push
