name: Bidirectional Sync Git and SVN
on: push
env:
  SVN_PASSWORD: ${{ vars.SVN_PASSWORD }}
  SVN_USERNAME: ${{ vars.SVN_USERNAME }}
  SVN_REPO_URL: ${{ vars.SVN_REPO_URL }}
jobs:
  sync_git_svn:
    runs-on: ubuntu-latest
    steps:
      - name: Install git-svn and SVN
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository ppa:git-core/ppa
          sudo apt-get update
          sudo apt-get install -y git-svn

      - name: Checkout Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create SVN Authentication File
        env:
          SVN_USERNAME: ${{ vars.SVN_USERNAME }}
          SVN_PASSWORD: ${{ vars.SVN_PASSWORD }}
        run: |
          mkdir -p ~/.subversion/auth/svn.simple
          cat <<EOF > ~/.subversion/auth/svn.simple/fba5e44bd62f064c71637fd742f1764d
          K 15
          svn:realmstring
          V 71
          <https://svn.informatik.uni-rostock.de:443> SVN  - ITMZ / IFI (Windows)
          K 8
          username
          V ${#SVN_USERNAME}
          ${SVN_USERNAME}
          K 8
          passtype
          V 6
          simple
          K 8
          password
          V ${#SVN_PASSWORD}
          ${SVN_PASSWORD}
          END
          EOF

      - name: Initialize and Fetch SVN Repository
        env:
          SVN_REPO_URL: ${{ vars.SVN_REPO_URL }}
          SVN_USERNAME: ${{ vars.SVN_USERNAME }}
        run: |
          cd test/
          git branch -m main
          git svn init https://svn.informatik.uni-rostock.de/lehre/ip2024/playground/ -T trunk -b branches -t tags --username de2403 --prefix=git-svn/
          git svn fetch --username "$SVN_USERNAME"

      - name: Rebase SVN Changes onto Git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --list
          git status
          if ! git diff --staged --quiet; then
            git config --global user.email "github-action@users.noreply.github.com"
            git config --global user.name "GitHub Action"
            git commit -m "Sync changes from SVN to Git"
            # Configure Git with token-based authentication
            git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
            git push
            echo "Changes from SVN committed and pushed to Git"
          else
            echo "No changes from SVN to sync to Git"
          fi

      - name: Sync Git Changes to SVN
        env:
          SVN_USERNAME: ${{ vars.SVN_USERNAME }}
        run: |
          git svn dcommit --username "$SVN_USERNAME"