name: Sync Git and SVN Repositories
on: push
jobs:
  sync_git_svn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install git-svn and SVN
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository ppa:git-core/ppa
          sudo apt-get update
          sudo apt-get install -y git
          sudo apt-get install -y git-svn

      - name: Sync changes from Git to SVN
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_REPO_URL: ${{ secrets.SVN_REPO_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global svn-remote.svn.url "https://${{ secrets.SVN_REPO_URL }}"
          git config --global svn-remote.svn.username "${{ secrets.SVN_USERNAME }}"
          git config --global svn-remote.svn.password "${{ secrets.SVN_PASSWORD }}"
          git svn init --trunk=trunk --branches=branches --tags=tags --no-auth-cache
          git rebase remotes/git-svn
          git svn dcommit

      - name: Sync changes from SVN to Git
        run: |
          # Ensure that we're up to date with the SVN repo
          git svn fetch --no-auth-cache --non-interactive

          # Sync SVN changes to the local Git repo
          git rebase remotes/git-svn

          # Commit and push any changes to Git
          git push
