name: Bidirectional Sync Git and SVN
on: push
env:
  SVN_PASSWORD: ${{ vars.SVN_PASSWORD }}
  SVN_USERNAME: ${{ vars.SVN_USERNAME }}
  SVN_REPO_URL: ${{ vars.SVN_REPO_URL }}
jobs:
  sync_git_svn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install git-svn and SVN
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository ppa:git-core/ppa
          sudo apt-get update
          sudo apt-get install -y git-svn

      - name: Create SVN Authentication File
        env:
          SVN_USERNAME: ${{ vars.SVN_USERNAME }}
          SVN_PASSWORD: ${{ vars.SVN_PASSWORD }}
        run: |
          mkdir -p ~/.subversion/auth/svn.simple
          cat <<EOF > ~/.subversion/auth/svn.simple/fba5e44bd62f064c71637fd742f1764d
          K 15
          svn:realmstring
          V 71
          <https://svn.informatik.uni-rostock.de:443> SVN  - ITMZ / IFI (Windows)
          K 8
          username
          V ${#SVN_USERNAME}
          ${SVN_USERNAME}
          K 8
          passtype
          V 6
          simple
          K 8
          password
          V ${#SVN_PASSWORD}
          ${SVN_PASSWORD}
          END
          EOF

      - name: Initialize and Fetch SVN Repository
        env:
          SVN_REPO_URL: ${{ vars.SVN_REPO_URL }}
          SVN_USERNAME: ${{ vars.SVN_USERNAME }}
        run: |
          # Initialize git-svn tracking for the SVN repository
          git svn init "$SVN_REPO_URL" -T trunk -b branches -t tags --username "$SVN_USERNAME"
          # Fetch all revisions from SVN
          git svn fetch --username "$SVN_USERNAME"

      - name: Rebase SVN Changes onto Git
        run: |
          # Rebase the SVN branch onto the current branch to ensure changes are synced
          git rebase remotes/git-svn --remote

      - name: Push SVN Changes to GitHub
        run: |
          # Push any new changes from SVN to GitHub
          git push origin HEAD:main

      - name: Sync Git Changes to SVN
        env:
          SVN_USERNAME: ${{ vars.SVN_USERNAME }}
        run: |
          # Rebase any new Git changes onto the SVN branch
          git rebase origin/main
          
          # Commit changes from Git to SVN
          git svn dcommit --username "$SVN_USERNAME"

      - name: Fetch and Push Final Changes from SVN to GitHub
        run: |
          # Fetch any new changes from SVN to ensure Git is up-to-date
          git svn fetch
          git rebase refs/remotes/git-svn

          # Push any remaining changes to GitHub
          git push origin HEAD:main
